# Generated by Django 4.2.11 on 2024-04-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="assembly_id",
            field=models.CharField(default="", max_length=256),
        ),
    ]
