# Generated by Django 4.2.11 on 2024-04-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_video_assembly_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="logo",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="text_in_video",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="transcription",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
