# Generated by Django 4.2.11 on 2024-04-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_video_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_id",
            field=models.CharField(default="", max_length=32),
        ),
    ]
