# Generated by Django 5.0.8 on 2025-04-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_video_logo_alter_video_text_in_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='video',
            name='text_in_video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='transcription',
        ),
    ]
